import type { Metadata } from "next";
import "./globals.css";
import { TracingBeam } from "@/components/ui/tracing-beam";
import Footer from "@/components/react-comp/Footer";
import Header from "@/components/react-comp/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-950">
        <Header />
        <TracingBeam>
          {children}
        </TracingBeam>
        <Footer />
      </body>
    </html>
  );
}
